name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update version in gradle.properties
        run: |
          echo "version=${{ steps.extract_version.outputs.version }}" > plugin/gradle.properties
          cat plugin/gradle.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew plugin:build plugin:test --no-daemon --stacktrace

      - name: Validate plugin
        run: ./gradlew plugin:validatePlugin --no-daemon

      - name: Publish to Gradle Plugin Portal (Dry Run)
        if: contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc')
        run: ./gradlew plugin:publishPlugins --dry-run --no-daemon
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

      - name: Publish to Gradle Plugin Portal
        if: "!contains(github.ref, 'alpha') && !contains(github.ref, 'beta') && !contains(github.ref, 'rc')"
        run: ./gradlew plugin:publishPlugins --no-daemon
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

      - name: Create GitHub Release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
          body: |
            ## Changes in ${{ steps.extract_version.outputs.version }}
            
            ### Added
            - New features and improvements
            
            ### Changed
            - Updates and modifications
            
            ### Fixed
            - Bug fixes
            
            ### Removed
            - Deprecated features removed
            
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.extract_version.outputs.version }}...HEAD