name: Test Release Process

on:
  workflow_dispatch:
    inputs:
      test_version:
        description: 'Test version to simulate'
        required: true
        default: '0.1.0-test'

jobs:
  test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Update version for testing
        run: |
          # Update version while preserving other properties
          sed -i "s/version=.*/version=${{ github.event.inputs.test_version }}/" plugin/gradle.properties
          echo "Testing with version: ${{ github.event.inputs.test_version }}"
          echo "Updated gradle.properties:"
          cat plugin/gradle.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew plugin:build plugin:test --no-daemon --stacktrace

      - name: Validate plugin
        run: ./gradlew plugin:validatePlugin --no-daemon

      - name: Dry run publish
        run: ./gradlew plugin:publishPlugins --dry-run --no-daemon
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-build-${{ github.event.inputs.test_version }}
          path: plugin/build/libs/